"""Core data types for the speqtro agent pipeline."""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Step:
    """A single reasoning step in a plan."""
    id: int
    description: str = ""
    tool: str = ""
    tool_args: dict = field(default_factory=dict)
    depends_on: list[int] = field(default_factory=list)
    status: str = "pending"  # pending, running, completed, failed
    result: Optional[dict] = None


@dataclass
class Plan:
    """A structured analysis plan."""
    query: str
    steps: list[Step] = field(default_factory=list)
    context: dict = field(default_factory=dict)

    def pending_steps(self) -> list[Step]:
        return [s for s in self.steps if s.status == "pending"]

    def is_complete(self) -> bool:
        return all(s.status in ("completed", "failed") for s in self.steps)


@dataclass
class ExecutionResult:
    """Result of executing a complete analysis plan."""
    plan: Plan
    summary: str = ""
    raw_results: dict = field(default_factory=dict)
    duration_s: float = 0.0
    iterations: int = 1
    metadata: dict = field(default_factory=dict)

    def to_markdown(self) -> str:
        lines = [
            f"# Analysis Report: {self.plan.query}",
            "",
            f"*Generated by speqtro in {self.duration_s:.1f}s*",
            "",
            "---",
            "",
            self.summary,
        ]
        return "\n".join(lines)
